# Generated by Django 5.0.3 on 2024-03-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
