# Generated by Django 5.0.3 on 2024-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_balance_user_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_or_promo_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
