# Generated by Django 5.0.3 on 2024-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_referral_or_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('referral', 'Referral bonus'), ('new_year', 'New year bonus')], max_length=20)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('promo_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('amount', models.FloatField(default=0.0)),
                ('validity_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('retailer', 'Retailer'), ('api_user', 'Api user'), ('user', 'User')], default='user', max_length=255),
        ),
    ]
