# Generated by Django 5.0.3 on 2024-04-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bonus_promocode_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
