# Generated by Django 5.0.3 on 2024-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonuce_type', models.CharField(choices=[('referral', 'Referral bonuce'), ('new_year', 'New year bonuce')], max_length=20)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bonus',
            new_name='bonuce',
        ),
    ]
