# Generated by Django 5.0.4 on 2024-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bonuce_delete_bonus_rename_bonus_user_bonuce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_or_promo_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
