# Generated by Django 5.0.3 on 2024-04-07 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('percentage', models.FloatField()),
                ('charge_type', models.CharField(choices=[('disbursement', 'Disburment charge')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=100)),
                ('account_reference', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('collection_channel', models.CharField(max_length=100)),
                ('reservation_reference', models.CharField(max_length=100)),
                ('reserved_account_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
                ('income_split_config', models.JSONField()),
                ('bvn', models.CharField(max_length=100)),
                ('nin', models.CharField(max_length=100)),
                ('restrict_payment_source', models.BooleanField()),
                ('accounts', models.ManyToManyField(to='paymentGateway.bankaccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('old_balance', models.FloatField(blank=True, null=True)),
                ('new_balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('debit', 'Debit Alert'), ('credit', 'Credit Alert')], max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
