# Generated by Django 5.0.3 on 2024-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
