# Generated by Django 5.0.3 on 2024-04-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0002_alter_transaction_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_account_name', models.CharField(max_length=255)),
                ('destination_bank_name', models.CharField(max_length=255)),
                ('destination_account_number', models.CharField(max_length=20)),
                ('destination_bank_code', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
