# Generated by Django 5.0.3 on 2024-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0003_disbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='settlement_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
