# Generated by Django 5.0.3 on 2024-04-14 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0004_transaction_charge_transaction_settlement_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='total_fee',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentGateway.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('card_transfer', 'Card transfer')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentGateway.transaction'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('refund_reference', models.CharField(max_length=255)),
                ('customer_note', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('destination_account_name', models.CharField(max_length=255)),
                ('destination_bank_name', models.CharField(max_length=255)),
                ('destination_account_number', models.CharField(max_length=20)),
                ('destination_bank_code', models.CharField(max_length=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentGateway.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_type', models.CharField(choices=[('permanent', 'Parmanent lock'), ('breakable_lock', 'Breakable lock')], max_length=20)),
                ('amount', models.FloatField(default=0.0)),
                ('maturity', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('once', 'once')], max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card mathod'), ('transfer', 'Transfer method'), ('wallet', 'Wallet method')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
