# Generated by Django 5.0.4 on 2024-05-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0006_saving_notification_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReferenceAndType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('saving', 'Saving reference'), ('funding', 'Funding reference')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit Alert'), ('credit', 'Credit Alert')], max_length=20, null=True),
        ),
    ]
