# Generated by Django 5.0.4 on 2024-05-16 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0007_transactionreferenceandtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingwallet',
            name='collection_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='savingwallet',
            name='with_penalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_type',
            field=models.CharField(choices=[('wallet_disbursement', 'Disburment charge'), ('permanent_saving_disbursement', 'Customer permanent saving disbursement earning'), ('temporary_saving_disbursement', 'Customer temporary saving disbursement earning'), ('saving_penalty', 'saving penalty')], max_length=255),
        ),
        migrations.AlterField(
            model_name='saving',
            name='collection_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='DisbursefromSavingWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('destination_account_name', models.CharField(max_length=255)),
                ('destination_bank_name', models.CharField(max_length=255)),
                ('destination_account_number', models.CharField(max_length=20)),
                ('destination_bank_code', models.CharField(max_length=10)),
                ('saving_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentGateway.savingtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefundFromSavingWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('refund_reference', models.CharField(max_length=255)),
                ('customer_note', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('destination_account_name', models.CharField(max_length=255)),
                ('destination_bank_name', models.CharField(max_length=255)),
                ('destination_account_number', models.CharField(max_length=20)),
                ('destination_bank_code', models.CharField(max_length=10)),
                ('saving_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentGateway.savingtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
