# Generated by Django 5.0.4 on 2024-04-23 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(choices=[('.....', '.........'), ('....', '.........'), ('...', '.........'), ('.....', '.........')], max_length=255, null=True)),
                ('network', models.CharField(choices=[('MTN', '.........'), ('Glo', '.........'), ('Airtel', '.........')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CableAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(choices=[('.....', '.........'), ('....', '.........'), ('...', '.........'), ('.....', '.........')], max_length=255, null=True)),
                ('plan_type', models.CharField(choices=[('DSTV', '.........'), ('StarTimes', '.........'), ('GOTV', '.........')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('percentage', models.FloatField()),
                ('charge_type', models.CharField(choices=[('data', 'Data Charge'), ('airtime', 'Airtime Charge'), ('bill', 'Bill Charge'), ('cable', 'Cable Charge')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', '.........'), ('Glo', '.........'), ('Airtel', '.........')], max_length=255, null=True)),
                ('plan_type', models.CharField(choices=[('ALL', '.........'), ('SME', '.........'), ('GIFTING', '.........')], max_length=255, null=True)),
                ('api', models.CharField(choices=[('.....', '.........'), ('....', '.........'), ('...', '.........'), ('.....', '.........')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityAPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(choices=[('.....', '.........'), ('....', '.........'), ('...', '.........'), ('.....', '.........')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyAirtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.IntegerField()),
                ('amount', models.FloatField(null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('airtime_type', models.CharField(max_length=255)),
                ('old_balance', models.FloatField(blank=True, null=True)),
                ('new_balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('amount', models.FloatField(null=True)),
                ('plan_id', models.CharField(max_length=255)),
                ('old_balance', models.FloatField(blank=True, null=True)),
                ('new_balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CableRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cablename_id', models.IntegerField(null=True)),
                ('cableplan_id', models.IntegerField(null=True)),
                ('smart_card_number', models.CharField(max_length=255, null=True)),
                ('old_balance', models.FloatField(blank=True, null=True)),
                ('new_balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco_name', models.IntegerField(null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('meter_number', models.BigIntegerField(null=True)),
                ('old_balance', models.FloatField(blank=True, null=True)),
                ('new_balance', models.FloatField(blank=True, null=True)),
                ('meter_type', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
