# Generated by Django 5.0.4 on 2024-04-25 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilityCart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyAirtime',
            new_name='AirtimeTransaction',
        ),
        migrations.RenameModel(
            old_name='BuyData',
            new_name='DataTransaction',
        ),
        migrations.RenameModel(
            old_name='ElectricityPayment',
            new_name='ElectricityTransaction',
        ),
        migrations.RenameModel(
            old_name='CableRecharge',
            new_name='RechargeTransaction',
        ),
        migrations.RenameField(
            model_name='cableapisetting',
            old_name='plan_type',
            new_name='cable',
        ),
        migrations.RemoveField(
            model_name='cableapisetting',
            name='api',
        ),
        migrations.RemoveField(
            model_name='dataapisetting',
            name='api',
        ),
        migrations.AddField(
            model_name='airtimeapisetting',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cableapisetting',
            name='api_name',
            field=models.CharField(choices=[('VTPass', 'VTPass Cable plan'), ('.....', '.........'), ('....', '.........'), ('...', '.........'), ('.....', '.........')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cableapisetting',
            name='api_url',
            field=models.CharField(choices=[('.....', 'VTPass dataPlan url'), ('.....', '.........'), ('....', '.........'), ('...', '.........'), ('.....', '.........')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cableapisetting',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataapisetting',
            name='api_name',
            field=models.CharField(choices=[('VTPass', 'VTPass Data API Endpoint'), ('.....', '.........'), ('....', '.........'), ('...', '.........'), ('.....', '.........')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataapisetting',
            name='api_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/service-variations?serviceID=mtn-data', 'VTPass mtn data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=airtel-data', 'VTPass airtel data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=glo-data', 'VTPass glo data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=etisalat-sme-data', 'VTPass 9-mobile data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=etisalat-sme-data', 'VTPass 9-mobile sme data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=smile-direct', 'VTPass smile data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=spectranet', 'VTPass spectranet data url'), ('.....', '.........'), ('....', '.........'), ('...', '.........'), ('.....', '.........')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataapisetting',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricityapisetting',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
