# Generated by Django 5.0.4 on 2024-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilityCart', '0003_dataplan_alter_airtimeapisetting_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataplan',
            name='network',
            field=models.CharField(choices=[(1, 'MTN'), (2, 'GLO'), (3, '9MOBILE'), (4, 'AIRTEL')], max_length=50),
        ),
    ]
