# Generated by Django 5.0.4 on 2024-05-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilityCart', '0004_alter_dataplan_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='CablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cableplan_id', models.CharField(max_length=50, unique=True)),
                ('cable', models.CharField(choices=[('GOTV', 'GOTV'), ('DSTV', 'DSTV'), ('STARTIME', 'STARTIME')], max_length=50)),
                ('package', models.CharField(max_length=100)),
                ('plan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
