# Generated by Django 5.0.4 on 2024-05-16 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilityCart', '0005_cableplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatransaction',
            old_name='network_id',
            new_name='network',
        ),
        migrations.RenameField(
            model_name='datatransaction',
            old_name='plan_id',
            new_name='plan_type',
        ),
        migrations.RemoveField(
            model_name='cableapisetting',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='dataapisetting',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='electricityapisetting',
            name='api',
        ),
        migrations.AddField(
            model_name='airtimeapisetting',
            name='purchase_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/service-variations?serviceID=mtn-data', 'VT-Pass Data Purchase url'), ('https://www.gongozconcept.com/api/topup/', 'Gongoz-concept Data Purchase url'), ('https://husmodata.com/api/topup/', 'Hosmo-data Data Purchase url'), ('https://www.gladtidingsdata.com/api/topup/', 'Glatiddings-sub Data Purchase url'), ('https://maskawasubapi.com/api/topup/', 'Maskawa-sub Data Purchase url')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cableapisetting',
            name='plans_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/service-variations?serviceID=dstv', 'VT-Pass dstv cable plans url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=startimes', 'VT-Pass startime cable plans url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=gotv', 'VT-Pass gotv cable plans url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=showmax', 'VT-Pass showmax plans url'), ('https://www.gongozconcept.com/api/user/', 'Gongoz-concept cable plans url'), ('https://husmodata.com/api/users/', 'Hosmo-data cable plans url'), ('https://www.gladtidingsdata.com/api/user/', 'Glatiddings-sub cable plans url'), ('https://maskawasubapi.com/api/users/', 'Maskawa-sub cable plans url')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cableapisetting',
            name='purchase_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/pay/', 'VT-Pass cable Purchase url'), ('https://www.gongozconcept.com/api/cablesub/', 'Gongoz-concept cable Purchase url'), ('https://husmodata.com/api/cablesub/', 'Hosmo-data cable Purchase url'), ('https://www.gladtidingsdata.com/api/cablesub/', 'Glatiddings-sub cable Purchase url'), ('https://maskawasubapi.com/api/cablesub/', 'Maskawa-sub cable Purchase url')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cableapisetting',
            name='validate_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/merchant-verify', 'VT-Pass electyricity validate url'), ('https://www.gongozconcept.com/api/validate_iuc', 'Gongoz-concept electricity validate url'), ('https://husmodata.com/api/validate_iuc', 'Hosmo-data electricity validate url'), ('https://www.gladtidingsdata.com/ajax/validate_iuc', 'Glatiddings-sub electricity validate url'), ('https://maskawasubapi.com/api/validate_iuc', 'Maskawa-sub electricity validate url')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataapisetting',
            name='plans_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/service-variations?serviceID=mtn-data', 'VTPass mtn data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=airtel-data', 'VTPass airtel data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=glo-data', 'VTPass glo data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=etisalat-data', 'VTPass 9-mobile data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=etisalat-sme-data', 'VTPass 9-mobile sme data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=smile-direct', 'VTPass smile data url'), ('https://api-service.vtpass.com/api/service-variations?serviceID=spectranet', 'VTPass spectranet data url'), ('https://www.gongozconcept.com/api/user/', 'Gongoz-concept url'), ('https://husmodata.com/api/users/', 'Hosmo-data url'), ('https://www.gladtidingsdata.com/api/user/', 'Glatiddings-sub url'), ('https://maskawasubapi.com/api/users/', 'Maskawa-sub url')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataapisetting',
            name='purchase_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/pay/', 'VT-Pass Data Purchase url'), ('https://www.gongozconcept.com/api/data/', 'Gongoz-concept Data Purchase url'), ('https://husmodata.com/api/data/', 'Hosmo-data Data Purchase url'), ('https://www.gladtidingsdata.com/api/data/', 'Glatiddings-sub Data Purchase url'), ('https://maskawasubapi.com/api/data/', 'Maskawa-sub Data Purchase url')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataapisetting',
            name='validate_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/merchant-verify', 'VT-Pass vaidate email for smile-direct url')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricityapisetting',
            name='api_name',
            field=models.CharField(choices=[('VT-Pass', 'VT-Pass API Endpoint'), ('gongoz-concept', 'Gongoz-concept API Endpoint'), ('maskawa-sub', 'Masakawa-sub API Endpoint'), ('hosmo-data', 'Hosmo-data API Endpoint'), ('sim-hosting', 'Sim-Hosting API Endpoint'), ('gladtiddings-data', 'Glatiddings-data API Endpoint')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricityapisetting',
            name='purchase_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/pay/', 'VT-Pass electyricity Purchase url'), ('https://www.gongozconcept.com/api/billpayment/', 'Gongoz-concept electricity Purchase url'), ('https://husmodata.com/api/billpayment/', 'Hosmo-data electricity Purchase url'), ('https://www.gladtidingsdata.com/api/billpayment/', 'Glatiddings-sub electricity Purchase url'), ('https://maskawasubapi.com/api/billpayment/', 'Maskawa-sub electricity Purchase url')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricityapisetting',
            name='validate_url',
            field=models.CharField(choices=[('https://api-service.vtpass.com/api/merchant-verify', 'VT-Pass electyricity validate url'), ('https://www.gongozconcept.com/api/validate_meter_number', 'Gongoz-concept electricity validate url'), ('https://husmodata.com/api/validate_meter_number', 'Hosmo-data electricity validate url'), ('https://www.gladtidingsdata.com/ajax/validate_meter_number', 'Glatiddings-sub electricity validate url'), ('https://maskawasubapi.com/api/validate_meter_number', 'Maskawa-sub electricity validate url')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='airtimeapisetting',
            name='api',
            field=models.CharField(choices=[('VT-Pass', 'VT-Pass API Endpoint'), ('gongoz-concept', 'Gongoz-concept API Endpoint'), ('maskawa-sub', 'Masakawa-sub API Endpoint'), ('hosmo-data', 'Hosmo-data API Endpoint'), ('sim-hosting', 'Sim-Hosting API Endpoint'), ('gladtiddings-data', 'Glatiddings-data API Endpoint')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='airtimeapisetting',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('Glo', 'Glo'), ('Airtel', 'Airtel'), ('Etisalat', '9-Mobile')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='airtimetransaction',
            name='network',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cableapisetting',
            name='api_name',
            field=models.CharField(choices=[('VT-Pass', 'VT-Pass API Endpoint'), ('gongoz-concept', 'Gongoz-concept API Endpoint'), ('maskawa-sub', 'Masakawa-sub API Endpoint'), ('hosmo-data', 'Hosmo-data API Endpoint'), ('sim-hosting', 'Sim-Hosting API Endpoint'), ('gladtiddings-data', 'Glatiddings-data API Endpoint')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataapisetting',
            name='api_name',
            field=models.CharField(choices=[('VT-Pass', 'VT-Pass API Endpoint'), ('gongoz-concept', 'Gongoz-concept API Endpoint'), ('maskawa-sub', 'Masakawa-sub API Endpoint'), ('hosmo-data', 'Hosmo-data API Endpoint'), ('sim-hosting', 'Sim-Hosting API Endpoint'), ('gladtiddings-data', 'Glatiddings-data API Endpoint')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CableTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cablename', models.IntegerField(null=True)),
                ('smart_card_number', models.CharField(max_length=255, null=True)),
                ('package', models.CharField(max_length=255, null=True)),
                ('old_balance', models.FloatField(blank=True, null=True)),
                ('new_balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RechargeTransaction',
        ),
    ]
